name: dart_des
description: This algorithm is a pure dart implementation of the DES and Triple DES algorithms.
version: 0.0.2
homepage: https://github.com/delletenebre/dart_des

environment:
  sdk: ">=2.7.0 <3.0.0"
